events {
    worker_connections  1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;
    root /var/www/;
    sendfile        on;
    keepalive_timeout  65;

    server {
        listen 80;
        server_name localhost;

        root /var/www/;
        index  index.html;

        location ../frontend/ {
            try_files $uri $uri/ /index.html;
        }

        location ../frontend/ {
        alias /var/www/;
        index index.html;
    }
    add_header Content-Security-Policy "upgrade-insecure-requests" always;
    }
}
